#include "EasyBMP.cpp"
#include "cpu_blur.cpp"
#include "cpu_sharpen.cpp"
#include "cpu_edges.cpp"
#include "cpu_emboss.cpp"
#include "cpu_sobel.cpp"
#include "cpu_black_and_white.cpp"
#include "gpu_blur.cu"
